project:
  type: website
  output-dir: _site

website: 
  title: "Meena Maharjan"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: experience.qmd
        text: Experience
      - href: research.qmd
        text: Research
      - href: projects/index.qmd
        text: Projects
      - href: publications.qmd
        text: Publications
      - href: skills.qmd
        text: Skills
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: cosmo
    css: styles/customs.css
    toc: false
    page-layout: full
